# Generated by Django 5.0.6 on 2024-06-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0004_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена курса"),
        ),
    ]
