# Generated by Django 5.0.6 on 2024-06-12 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0005_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_subscription",
                to="lms_app.course",
                verbose_name="Курс",
            ),
        ),
    ]
